### ISSUE TITLE
大佬，有个关于镜像的问题想要请教

### ISSUE THREAD

**Issue by xjDUAN184** [Tlntin/Qwen-7B-Chat-TensorRT-LLM#1]
您这里说比赛的镜像已经下架了，但是可以直接通过编译实现，是什么意思啊？方便具体说下吗？

**Comment by Tlntin** [comment]
![image](https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/assets/28218658/dca36282-f634-4bde-963c-4287ffc199df)
在项目路径，运行这个命令，可以编译出docker镜像。
