### ISSUE TITLE
关于paged_kv_cache的疑问？

### ISSUE THREAD

**Issue by Coder-nlper** [Tlntin/Qwen-7B-Chat-TensorRT-LLM#13]
paged_kv_cache是VLLM里面提出的paged Attention 概念的实现吗？

对于Smooth量化后，启用paged_kv_cache速度还慢了一些

未启用时候，生成大约 50 tokens/s，显存占用 10GB左右
启用时候，生成速度大约 46 tokens/s，显存占用基本满了，21GB左右

VLLM目前没有Smooth量化相关实现，VLLM纯跑FP16的，速度大约是29 tokens/s

如果paged_kv_cache是VLLM里面的实现，对于KVcache进行了优化，那smoothquant量化后，速度不应比不启用的时候慢呀

测试环境：A10 * 4

**Comment by Tlntin** [comment]
paged_kv_cached目前有两个已知问题：
1. python下推理显存溢出。
2. python下推理速度更慢，参考该[issue](https://github.com/NVIDIA/TensorRT-LLM/issues/75)

目前nvidia官方人员推荐是用triton部署，用c++做推理，可以解决该问题。
具体可以参考该[文档](https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/blob/release/0.5.0/docs/triton_deploy_trt-llm.md)

**Comment by Coder-nlper** [comment]
> paged_kv_cached目前有两个已知问题：
> 
> 1. python下推理显存溢出。
> 2. python下推理速度更慢，参考该[issue](https://github.com/NVIDIA/TensorRT-LLM/issues/75)
> 
> 目前nvidia官方人员推荐是用triton部署，用c++做推理，可以解决该问题。 具体可以参考该[文档](https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/blob/release/0.5.0/docs/triton_deploy_trt-llm.md)

好的。感谢大佬回复
