### ISSUE TITLE
能导出镜像吗？

### ISSUE THREAD

**Issue by shifop** [Tlntin/Qwen-7B-Chat-TensorRT-LLM#14]
构建docker镜像有点麻烦，经常连接超时。可以导出镜像放网盘吗，^~^

**Comment by Tlntin** [comment]
不同gpu编译的gpu可能还不通用，这也是为啥nvidia还没放出镜像的原因，所以建议短期还是自己编译会更好。

**Comment by Tlntin** [comment]
要镜像，还是等nvidia的官方镜像，他们会重复测试不同gpu的兼容性。

**Comment by shifop** [comment]
我的是3090

**Comment by Tlntin** [comment]
巧了，我也有一个3090。
最后确认一下，放dockerhub或者阿里云的公开镜像会不会好一些？
只能接受百度网盘？
因为用百度网盘我怕可能传完就损坏了，因为文件会很大。
前者能减少一些重复layer，减少上传内容，并且下发很方便。

**Comment by shifop** [comment]
放hub上可以呀~

**Comment by Tlntin** [comment]
ok，那我传dockerhub。
你如果下载不了，就用第三方dockerhub拉下来。

**Comment by shifop** [comment]
你这边是怎么构建的，我试着修改dockerfile，加了代理，换国内源，还是失败

**Comment by shifop** [comment]
> ok，那我传dockerhub。 你如果下载不了，就用第三方dockerhub拉下来。

🆗，感谢🙇‍

**Comment by Tlntin** [comment]
我直接放triton_trt_llm的镜像了，方便你编译+部署，一条龙服务。

**Comment by Tlntin** [comment]
已上传镜像到阿里云
```bash
docker pull registry.cn-guangzhou.aliyuncs.com/tlntin/triton_trt_llm:v0.5.0
```

**Comment by Tlntin** [comment]
> 你这边是怎么构建的，我试着修改dockerfile，加了代理，换国内源，还是失败

直接构建的咯，我这`网络好`

**Comment by maozixi1** [comment]
> 已上传镜像到阿里云
> 
> ```shell
> docker pull registry.cn-guangzhou.aliyuncs.com/tlntin/triton_trt_llm:v0.5.0
> ```



> 已上传镜像到阿里云
> 
> ```shell
> docker pull registry.cn-guangzhou.aliyuncs.com/tlntin/triton_trt_llm:v0.5.0
> ```

请问有编译好的0.7.0 版本的triton_trt_llm 镜像， 显卡也是3090
