### ISSUE TITLE
qwen14bchat int4转换后输出异常

### ISSUE THREAD

**Issue by Minami-su** [Tlntin/Qwen-7B-Chat-TensorRT-LLM#18]
qwen14bchat在执行python3 build.py --use_weight_only --weight_only_precision=int4后执行python run.py 推理输出的结果异常，输出了一堆代码，或许是因为14b的模型代码跟之前的7b代码不一致，但是还是希望能解决一下
Input: "<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
你好，请问你叫什么？<|im_end|>
<|im_start|>assistant
"
Output: "added by the user
@throws Exception
public function loadTemplate($file)
    {
        if (!file_exists($file)) {
            throw new Exception("The template file $file does not exist.");
        }

        $this->template = file_get_contents($file);
    },-->>>

public function execute()
    {
        $this->table = $this->model->getTableName();
        $this->columns = $this->model->getColumns();
        $this->data = $this->model->getData();
        $this->result = $this->model->getResult();
        
这堆代码是模型的输出结果，不是报错，输出的结果异常

**Comment by Tlntin** [comment]
😅明天我测试一下，看看是不是14b又更新了。

**Comment by Tlntin** [comment]
请问一下int8是否正常呢？
您用的是什么显卡呢？

**Comment by Minami-su** [comment]
显卡2080ti 22g，int8没试，

**Comment by Minami-su** [comment]
我没有执行这部分
![image](https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/assets/76865636/8ae3569f-1231-4ffa-8aea-0e2245b72867)
我直接把qwen文件夹拉到在官方编译好的容器里的，有没有影响？

**Comment by Tlntin** [comment]
> 显卡2080ti 22g，int8没试，

Trt-llm不支持20系，测试过会乱码。
官方截图说明:
![1698320714700.jpg](https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/assets/28218658/a489cecd-3a2f-44d0-bfa9-4fd4341d4d8b)

**Comment by Minami-su** [comment]
呜呜😭，好吧，谢谢你

**Comment by Tlntin** [comment]
> 呜呜😭，好吧，谢谢你

不客气，实在要体验可以试试AutoDL，参考[文章](https://zhuanlan.zhihu.com/p/663915644)
需要编译好的镜像也可以直接和我说，我可以分享给你，不过需要你提供AutoDL id。

**Comment by Minami-su** [comment]
> > 呜呜😭，好吧，谢谢你
> 
> 不客气，实在要体验可以试试AutoDL，参考[文章](https://zhuanlan.zhihu.com/p/663915644) 需要编译好的镜像也可以直接和我说，我可以分享给你，不过需要你提供AutoDL id。

我的id  aa60e613-d873-4b95-ba3a-0bcc0ceae35b

**Comment by Tlntin** [comment]
> aa60e613-d873-4b95-ba3a-0bcc0ceae35b

ok，已共享镜像。

**Comment by Minami-su** [comment]
> > aa60e613-d873-4b95-ba3a-0bcc0ceae35b
> 
> ok，已共享镜像。

谢谢大佬，😭

**Comment by Tlntin** [comment]
不客气。

**Comment by Minami-su** [comment]
> 不客气。

https://github.com/NVIDIA/TensorRT-LLM/issues/278#issuecomment-1794021837我在20系显卡上解决了这个问题，有关编译乱码的问题

**Comment by Tlntin** [comment]
> > 不客气。
> 
> https://github.com/NVIDIA/TensorRT-LLM/issues/278#issuecomment-1794021837我在20系显卡上解决了这个问题，有关编译乱码的问题
> 

6
