### ISSUE TITLE
Support int4 gptq and awq quantization?

### ISSUE THREAD

**Issue by Yangruipis** [Tlntin/Qwen-7B-Chat-TensorRT-LLM#20]
hi, is there any plan to support int4 gptq and awq quantization? 

thank you for your awesome work!

**Comment by Tlntin** [comment]
not support now!

**Comment by Sanster** [comment]
gptq support：https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/pull/26

**Comment by Tlntin** [comment]
awq supported!  commit: https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/commit/4f124cfa148a997025e60b2bca7bfb967f2528e4
