### ISSUE TITLE
AttributeError: 'QWenConfig' object has no attribute 'intermediate_size'

### ISSUE THREAD

**Issue by ThinkPadRiver** [Tlntin/Qwen-7B-Chat-TensorRT-LLM#25]
$python3 build.py --remove_input_padding --enable_context_fmha
Traceback (most recent call last):
  File "/usr/local/Qwen-7B-Chat-TensorRT-LLM/qwen/build.py", line 713, in <module>
    args = parse_arguments()
  File "/usr/local/Qwen-7B-Chat-TensorRT-LLM/qwen/build.py", line 404, in parse_arguments
    args.inter_size = hf_config.intermediate_size  # override the inter_size for QWen
  File "/opt/conda/lib/python3.10/site-packages/transformers/configuration_utils.py", line 261, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'QWenConfig' object has no attribute 'intermediate_size'

这是为啥呢

**Comment by Tlntin** [comment]
模型放了吗？qwen_7b_chat

**Comment by ThinkPadRiver** [comment]
> 模型放了吗？qwen_7b_chat

放了的，不过这个问题已经解决了。想咨询另外一个问题，我这边的镜像运行在集群上，集群上的GPU驱动版本还是CUDA11.4对应的470.82版本，编译的时候提示驱动版本过低，但是升级集群上的驱动又太麻烦，需要推动另外一个团队操作，TensorRT-LLM在这个版本上能够运行吗？

**Comment by Tlntin** [comment]
> > 模型放了吗？qwen_7b_chat
> 
> 放了的，不过这个问题已经解决了。想咨询另外一个问题，我这边的镜像运行在集群上，集群上的GPU驱动版本还是CUDA11.4对应的470.82版本，编译的时候提示驱动版本过低，但是升级集群上的驱动又太麻烦，需要推动另外一个团队操作，TensorRT-LLM在这个版本上能够运行吗？

不能，需要升级驱动到535以上

**Comment by ThinkPadRiver** [comment]
> > > 模型放了吗？qwen_7b_chat
> > 
> > 
> > 放了的，不过这个问题已经解决了。想咨询另外一个问题，我这边的镜像运行在集群上，集群上的GPU驱动版本还是CUDA11.4对应的470.82版本，编译的时候提示驱动版本过低，但是升级集群上的驱动又太麻烦，需要推动另外一个团队操作，TensorRT-LLM在这个版本上能够运行吗？
> 
> 不能，需要升级驱动到535以上

好的，多谢了

**Comment by LinqiY** [comment]
> > 模型放了吗？qwen_7b_chat
> 
> 放了的，不过这个问题已经解决了。想咨询另外一个问题，我这边的镜像运行在集群上，集群上的GPU驱动版本还是CUDA11.4对应的470.82版本，编译的时候提示驱动版本过低，但是升级集群上的驱动又太麻烦，需要推动另外一个团队操作，TensorRT-LLM在这个版本上能够运行吗？

您好，'QWenConfig' object has no attribute 'intermediate_size'这个问题是如何解决的呢？
