### ISSUE TITLE
部署api和尝试网页对话出现的bug

### ISSUE THREAD

**Issue by Astrallee** [Tlntin/Qwen-7B-Chat-TensorRT-LLM#27]
在配置api时，文章提供的四中调用方式，依次进行尝试，async_client 、normal_client.py、openai_normal_client.py皆可正常运行。

openai_stream_client.py首先成功进入指令行，但是在进行交互时会爆出如下错误。
python openai_stream_client.py 窗口错误如下
![image](https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/assets/48097779/8686f42e-720e-47db-8959-6da9480a71af)

在python api.py 窗口错误如下
![image](https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/assets/48097779/5301a8f3-6eb7-4b97-aea0-addb3b77236c)

同样的在运行python web_demo.py命令时，webui界面正常开启，但是在交互时爆出上述类似的错误
在python web_demo.py窗口下
![image](https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/assets/48097779/beccf6e4-c366-43b5-8555-5ec61d19cf77)
在python api.py窗口下
![image](https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/assets/48097779/188413ad-34f4-4dc0-8652-bb50c9a1bdce)
似乎两个问题都是由同样的问题引起的，缺少model_dump_json

**Comment by Tlntin** [comment]
检查你下面这个`pydantic`包，需要大于2.3.2：
```bash
ip list | grep pydantic
pydantic                      2.4.2
pydantic_core                 2.10.1
```

**Comment by Tlntin** [comment]
同类型bug，[issue](https://github.com/QwenLM/Qwen/issues/229)

**Comment by Astrallee** [comment]
> 检查你下面这个`pydantic`包，需要大于2.3.2：
> 
> ```shell
> $pip list | grep pydantic
> pydantic                      2.4.2
> pydantic_core                 2.10.1
> ```

很感谢！！更新至2.4.2 已解决！
