### ISSUE TITLE
咨询个关于中间产物的问题

### ISSUE THREAD

**Issue by ThinkPadRiver** [Tlntin/Qwen-7B-Chat-TensorRT-LLM#29]
模型转换成FT格式之后，可以直接启动吗？

**Comment by zhaohb** [comment]
直接启动具体指的是什么呢，直接使用ft格式推理吗？如果是这种事不可以的，还是需要把ft build成engine之后才可以

**Comment by ThinkPadRiver** [comment]
比如我只想把模型转换成FT格式，不做进一步转化，直接用转换后的模型做推理

**Comment by Tlntin** [comment]
> 比如我只想把模型转换成FT格式，不做进一步转化，直接用转换后的模型做推理

并不可以，转出来的只是权重信息，没有推理能力。
