### ISSUE TITLE
显存占用

### ISSUE THREAD

**Issue by DunguLock** [Tlntin/Qwen-7B-Chat-TensorRT-LLM#30]
请教一个问题。
Qwen 7B 模型参数就需要占用 14G；
看代码中如果要是用 int4 或者 int8，都是需要先 load fp16 的权重，然后再通过一个算子处理得到量化后的权重。这个时候显存肯定会爆炸。不知道你们是否有测试过显存占用情况。

**Comment by Tlntin** [comment]
用cpu加载hf版咯
