### ISSUE TITLE
Question: 关于 gptq 和 awq 某个 bug fix 的效果

### ISSUE THREAD

**Issue by Sanster** [Tlntin/Qwen-7B-Chat-TensorRT-LLM#36]
hi，我看到这个 commit 中对量化加载权重过程进行了修改，想问下这个修改的影响是什么，是能够提高 int4 模型的效果还是能省显存之类的？感谢

https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/commit/95511613595c2fca8cd9071faf3695efe0d4da4a

**Comment by Tlntin** [comment]
用于多卡的，和单卡无瓜。
