### ISSUE TITLE
测试问题

### ISSUE THREAD

**Issue by Coder-nlper** [Tlntin/Qwen-7B-Chat-TensorRT-LLM#7]
新版v0.5.0分支，我看是使用了原版TensorRT-LLM，是不是并没有你优化过的东西？像一些cuda代码的修改

我使用的原版TensorRT-LLM进行构建

W4A16量化情况下，只有87tokens/s，没有239.98 tokens/s，我只测试单条，输入长度77，输出长度31

**Comment by Coder-nlper** [comment]
测试环境：
阿里云  A10  * 4，   内存 740GB

**Comment by Tlntin** [comment]
`是不是并没有你优化过的东西？像一些cuda代码的修改`
是的，之前修改的东西，官方都内置进去了，所以我就直接用原版了。

**Comment by Tlntin** [comment]
`W4A16量化情况下，只有87tokens/s，没有239.98 tokens/s，我只测试单条，输入长度77，输出长度31`
第二个问题：可以看看具体的性能表，单batch应该是达不到的，得多batch。
https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM#%E6%80%A7%E8%83%BD
而且我也是用benchmark测了很多条得到的平均结果，单条可能不准确。

**Comment by Coder-nlper** [comment]
> `W4A16量化情况下，只有87tokens/s，没有239.98 tokens/s，我只测试单条，输入长度77，输出长度31`
> 第二个问题：可以看看具体的性能表，单batch应该是达不到的，得多batch。
> https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM#%E6%80%A7%E8%83%BD
> 而且我也是用benchmark测了很多条得到的平均结果，单条可能不准确。
> 并且太短的文本，测试的意义不大。

👌，谢谢

**Comment by Coder-nlper** [comment]
我发现一个问题：
https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/blob/release/0.5.0/qwen/benchmark.py
<img width="524" alt="image" src="https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/assets/7296788/32fa7db0-30d4-4c7e-b6b6-cc530dc5ccf8">
这里面统计的时候把输入的token也算上了，我的统计是只算新生成的tokens。
我算上输入token长度的话。4bit量化速度 302 tokens/s

**Comment by Tlntin** [comment]
是的，算的时候是应该需要算输入的token，因为输入的token也是需要做处理的，输入越长，时间越长，所以计算的时候需要加上这个。
