### ISSUE TITLE
启动build时调用了Hugging face了吗？

### ISSUE THREAD

**Issue by zhanghui-china** [Tlntin/Qwen-7B-Chat-TensorRT-LLM#9]
python3 build.py --use_weight_only --weight_only_precision=int8

报loading weights from HF Qwen。。。
我已经把 模型文件复制到本地了，它还在连HF吗？

**Comment by zhanghui-china** [comment]
![image](https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/assets/63148804/647ba54c-246a-43bf-adf3-59d47a9d6d29)

**Comment by zhanghui-china** [comment]
我这里用的是16G显存。前面步骤都跟readme一致。

**Comment by Tlntin** [comment]
没有，这个是转权重，正常状况。

**Comment by zhanghui-china** [comment]
那这一步 loading weights from HF Qwen。。
我是该耐心等待吗？我怕它会去连HF下载模型。

**Comment by Tlntin** [comment]
大概等个2-5分钟就可以了。

**Comment by zhanghui-china** [comment]
好的。我试下。

**Comment by Tlntin** [comment]
加了一个进度条，防止类似疑问
![image](https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/assets/28218658/c644ec07-778a-465e-9dc9-793faa0d67d5)
